Restyled by shfmt

diff --git a/apktoolv2.4.0/apktool b/apktoolv2.4.0/apktool
--- a/apktoolv2.4.0/apktool
+++ b/apktoolv2.4.0/apktool
@@ -22,29 +22,28 @@
 # and set up progdir to be the fully-qualified pathname of its directory.
 prog="$0"
 while [ -h "$prog" ]; do
-    newProg=`/bin/ls -ld "$prog"`
+  newProg=$(/bin/ls -ld "$prog")
 
-    newProg=`expr "$newProg" : ".* -> \(.*\)$"`
-    if expr "x$newProg" : 'x/' >/dev/null; then
-        prog="$newProg"
-    else
-        progdir=`dirname "$prog"`
-        prog="$progdir/$newProg"
-    fi
+  newProg=$(expr "$newProg" : ".* -> \(.*\)$")
+  if expr "x$newProg" : 'x/' >/dev/null; then
+    prog="$newProg"
+  else
+    progdir=$(dirname "$prog")
+    prog="$progdir/$newProg"
+  fi
 done
-oldwd=`pwd`
-progdir=`dirname "$prog"`
+oldwd=$(pwd)
+progdir=$(dirname "$prog")
 cd "$progdir"
-progdir=`pwd`
-prog="$progdir"/`basename "$prog"`
+progdir=$(pwd)
+prog="$progdir"/$(basename "$prog")
 cd "$oldwd"
 
 jarfile=apktool.jar
 libdir="$progdir"
-if [ ! -r "$libdir/$jarfile" ]
-then
-    echo "$(basename "$prog"): can't find $jarfile"
-    exit 1
+if [ ! -r "$libdir/$jarfile" ]; then
+  echo "$(basename "$prog"): can't find $jarfile"
+  exit 1
 fi
 
 javaOpts=""
@@ -52,7 +51,7 @@ javaOpts=""
 # If you want DX to have more memory when executing, uncomment the following
 # line and adjust the value accordingly. Use "java -X" for a list of options
 # you can pass here.
-# 
+#
 javaOpts="-Xmx512M -Dfile.encoding=utf-8"
 
 # Alternatively, this will extract any parameter "-Jxxx" from the command line
@@ -60,18 +59,18 @@ javaOpts="-Xmx512M -Dfile.encoding=utf-8"
 # add a command-line parameter such as "-JXmx256M" in your ant scripts, for
 # example.
 while expr "x$1" : 'x-J' >/dev/null; do
-    opt=`expr "$1" : '-J\(.*\)'`
-    javaOpts="$javaOpts -$opt"
-    shift
+  opt=$(expr "$1" : '-J\(.*\)')
+  javaOpts="$javaOpts -$opt"
+  shift
 done
 
-if [ "$OSTYPE" = "cygwin" ] ; then
-	jarpath=`cygpath -w  "$libdir/$jarfile"`
+if [ "$OSTYPE" = "cygwin" ]; then
+  jarpath=$(cygpath -w "$libdir/$jarfile")
 else
-	jarpath="$libdir/$jarfile"
+  jarpath="$libdir/$jarfile"
 fi
 
 # add current location to path for aapt
-PATH=$PATH:`pwd`;
-export PATH;
+PATH=$PATH:$(pwd)
+export PATH
 exec java "$javaOpts" -jar "$jarpath" "$@"
